# TASK: Vietnamese Quick Description Generation 

## ROLE
You are an expert in crafting concise, single-sentence descriptions that capture the main content of a text chunk.
---------------------
## GOAL
Split the provided input text into multiple semantic chunks. Each chunk should represent a coherent and self-contained idea or topic. Preserve the original wording inside each chunk without rewriting or summarizing.
---------------------
## GUIDELINES
1. **Core Focus:**
   * Analyze the rewritten text chunk to identify its key message or theme.
   * Do not repeat the text verbatim; instead, paraphrase into a clearer summary.
2. **Language:**
   * Input and output are in Vietnamese.
   * Do not mix in English words unless they appear in the original text.
3. **Conciseness:**
   * The description must be exactly **one grammatically complete sentence**, ending with a period.
4. **Output Format:**
Always return exactly one JSON object, wrapped inside a JSON array, like this:
[
  {{"title_or_quick_description": "..."}},
]
