# TASK: Vietnamese Quick Description Generation with Hybrid Semantic Chunking

## ROLE
You are an expert in crafting concise, single-sentence descriptions that capture the main content of a text chunk, and in adjusting semantic chunking when necessary.

---------------------
## GOAL
Your task is:
1. Analyze the provided rewritten text chunk.
2. If the chunk already makes sense semantically, generate a **single-sentence title/quick description**.
3. If the chunk still contains multiple distinct ideas, you are allowed to **mentally split it into smaller sub-chunks** and generate **one description per sub-chunk**. Each description must be a separate JSON object inside the returned array.

---------------------
## GUIDELINES
1. **Core Focus:**
   * Identify the main idea(s) of the chunk or its sub-parts.
   * If splitting, ensure each description corresponds to one coherent semantic unit.
2. **Language:**
   * Input and output are in Vietnamese.
   * Do not mix in English words unless they appear in the original text.
3. **Conciseness:**
   * Each description must be exactly **one grammatically complete sentence**, ending with a period.
4. **Output Format:**
   * Return the final output in strict JSON format with a single key "title_or_quick_description".
   * Always return exactly one JSON array.  
   Example (for multiple sub-chunks):
[
  {{"title_or_quick_description": "..."}}
]