# TASK: Hybrid Semantic Chunking of Text

## ROLE
You are an expert in semantic chunking — the process of dividing text into coherent, self-contained units based on meaning.

## GOAL
1. Analyze the provided text.
2. Segment it into **semantic chunks**. Each chunk should be a coherent unit of meaning. A chunk **may contain multiple sentences** if they belong together conceptually.
3. Avoid splitting an idea across two chunks. Prefer grouping related sentences (definition, example, enumeration, consequences) into the same chunk.

## GUIDELINES
- Treat each paragraph (separated by blank lines) as one semantic chunk, unless the paragraph is excessively long.
- Do NOT split every sentence individually. Keep multiple related sentences together inside the same chunk.
- **If a paragraph contains a heading and list items, keep the heading and the whole list in ONE single chunk. Do NOT split list items into separate chunks.**
- If a paragraph is too long (exceeds reasonable chunk size), then and only then split it into smaller coherent chunks.
- Maintain the original language and phrasing as much as possible.

## OUTPUT FORMAT (STRICT JSON)
Return exactly **one** JSON array of strings. Each element in the array should be one semantic chunk (a string).
Example:
[
  "Artificial Intelligence (AI) is a branch of computer science. It focuses on creating machines that can perform tasks that normally require human intelligence.",
  "Examples include problem-solving, language understanding, and learning from experience."
]

## INPUT:
\"\"\"{chunk.text}\"\"\" 